### ISSUE TITLE
Simulação implantação Mike

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/new-portfolio#1]
- [ ] Implantar mkdcos.
- [ ] Implantar mike.
- [ ] Implantar actions para publicar versão conforme nome branch (new branch).
- [ ] Implantar actions para despublicar versão conforme exclusão de branch.

**Comment by gabrielbdornas** [comment]
- A fase para implantar o mkdocs e material no repositório não teve nenhuma surpresa.
- Implantar mike também correu tudo bem.
- Retirar o seletor de versão mike, por sua vez, não funcionou.
  - [Esta parte da configuração](https://github.com/jimporter/mike#configuration) sugerida na documentação não funcionou.
  - Enviei um [pedido de ajuda](https://github.com/jimporter/mike/issues/151#issuecomment-1806459699) para uma pessoa que parece ter resolvido o problema.
  - Usei `mike deploy 0.1`, `mike deploy 0.2 latest` e `mike set-default latest`.
- Sobre actions testei o [act](https://github.com/nektos/act).
  - Já havia instalado uma instenção para CLI `gh`.
  - Para utilizar devo, então, `gh act comando` (sendo comando issue, pr). Depois terei que descobrir como selecionar um comando caso haja mais de um.
  - Comando `gh act -l` lista os actions do repositório.
  -  Comando `gh act <event>` roda o comando localmente com auxílio do docker.
  - O actions testado foi:

```yml
# This uses a reusable workflow
name: Get issue info

on:
  issues:
    types: [opened]

jobs:
  get_issue_info:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue body: ${{ github.event.issue.labels }}"
          echo "branch: ${{ github.ref_name }}"
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
```

  - Ele me mostrou que `${{ github.ref_name }}` retorna o nome da branch que estou trabalhondo. Sendo assim, poderi trabalhar com `mike publish ${{ github.ref_name }}` para publicar novas versões de teste.
